service: ${self:provider.stage}-users-${self:custom.common.apiVersion}

custom:
  common: ${file(../../../infra/scripts/sls-common.js)}

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: go1.x

package:
  individually: true
  exclude:
    - "*/**"

functions:
  users:
    handler: lambda/http/bin/main
    package:
        include:
          - lambda/http/bin/main
    environment: ${self:custom.common.env}
    events:
      - http:
          method: GET
          path: /me
