service: ${self:provider.stage}-users-${self:custom.common.apiVersion}

custom:
  common: ${file(../../../infra/scripts/sls-common.js)}

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  users:
    handler: bin/users
    environment: ${self:custom.common.env}
    events:
      - http:
          method: GET
          path: /me
